runtime: nodejs16
inbound_services:
  - warmup
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50